version: 0.2

phases: 
  install:
    runtime-versions:
       python: 3.9 #install Python 3.9
  pre_build:
    commands:  
     - echo Joseph Mbatchou
     - python --version
  build: 
    commands:
      - echo ****Build started on 'date' ****
      - ls -al
      - echo Building phase on the way 
       
  post_build:
    commands: 
      - echo Build completed on 'date'
      - echo completed on 'time'
artifacts:
  files:
    - '**/*' #zip        
    